# Generated by Django 3.0.3 on 2022-01-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220113_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pageOrder',), 'verbose_name_plural': 'Catgeories'},
        ),
        migrations.AddField(
            model_name='category',
            name='pageOrder',
            field=models.IntegerField(default=0),
        ),
    ]
